name: complexapps-2024
channels:
  - conda-forge
  - defaults
  - fastai
dependencies:
  - annotated-types
  - bqplot
  - fastcore
  - ipydatagrid
  - ipyfilechooser
  - ipykernel
  - ipywidgets>8
  - matplotlib
  - jupyter
  - jupyterlab
  - notebook
  - nbdev
  - openpyxl
  - pandas
  - pydantic
  - python=3.11
  - statsmodels
  - traittypes
  - voila>=0.5.6
  - pip
    - ipyautoui
