name: complexapps-2024
channels:
  - conda-forge
  - defaults
  - fastai
dependencies:
  - fastcore=1.5.43
  - ipywidgets>8
  - matplotlib
  - ipykernel
  - jupyter
  - jupyterlab
  - notebook
  - nbdev=2.3.25
  - pandas
  - python=3.11
  - statsmodels
  - voila
