name: widgets-2024
channels:
  - conda-forge
  - defaults
  - fastai
dependencies:
  - ipywidgets >8
  - matplotlib
  - pandas
  - jupyterlab
  - ipykernel
  - jupyter
  - voila
  - notebook
  - nbdev=2.3.25
  - python=3.11
  - fastcore=1.5.43
  - statsmodels
